from .simple_serializer import SurtidorSimpleSerializer, BombaSimpleSerializer
from .surtidor_viewset import SurtidorViewset, SurtidorSerializer
from .bomba_viewset import BombaViewset, BombaSerializer
from .tipo_combustible_viewset import TipoCombustibleViewset, TipoCombustibleSerializer
